[package]
name = "hs_stats"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.7"
reqwest = { version = "0.11", features = ["blocking"] }
rusty-tesseract = "1.1.9"

